---
# .cpanel.yml for automatic deployment to Namecheap cPanel

# Branch to deploy
branch: main

# Tasks to run during deployment
deployment:
  tasks:
    - export DEPLOY_PATH=~/public_html
    - echo "Deploying repository to $DEPLOY_PATH"
    - cp -R * $DEPLOY_PATH
